@extends('layouts.public_layout')
@section('content')
	<div class="container">
		<h1>Terms and conditions</h1>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit laborum magni rem eos doloremque alias consectetur et laboriosam aperiam nemo dolor tenetur, neque, dolorum vel accusantium id, porro libero cumque!
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque non doloribus minus temporibus delectus quos nihil aliquam explicabo eligendi! Cum sint, quod exercitationem dignissimos? Ex voluptate, dicta aliquam saepe atque veniam quaerat assumenda, veritatis, facere rem magnam. In praesentium velit aut, perspiciatis provident porro vel. At unde enim, accusantium officiis.
		</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora, magni, laborum? Doloribus distinctio hic autem maxime molestias itaque reiciendis blanditiis, eius repellendus ut cumque quibusdam mollitia placeat nisi a eligendi sint totam natus ea ipsa temporibus doloremque dolore. Eius reiciendis eos natus, quidem cumque veritatis amet similique voluptates quia doloremque.</p>
		<p>Esse aspernatur eos quaerat assumenda nostrum asperiores, nisi consequuntur aut quod ex obcaecati. Accusamus mollitia consectetur neque temporibus minus nobis exercitationem, iure non pariatur magni quod natus officia asperiores maxime quaerat cum delectus provident voluptatem consequatur iste soluta eveniet reprehenderit doloremque voluptate. Eligendi esse quidem nihil nesciunt dolor tenetur maxime.</p>
		<p>Aliquid facere optio quis error dolor, nemo eum fuga ducimus obcaecati, perspiciatis accusantium itaque nisi consequatur placeat, in repudiandae minima vero ullam. Sint aliquam ullam vitae laboriosam quos consectetur repudiandae itaque incidunt eos nulla tenetur voluptates nihil sit maxime natus dolorem dolore repellendus possimus voluptatum corporis, laborum saepe, similique fugit!</p>
		<p>Vitae quaerat, dignissimos laborum sequi praesentium nisi animi, quas distinctio soluta, qui, voluptatum. Quisquam provident, laudantium pariatur deserunt? Deleniti ex veniam quasi, iusto libero unde sapiente laborum, dignissimos eligendi aut, non, expedita beatae molestias voluptatibus! Soluta, quaerat odit nostrum suscipit dignissimos error sit quam sapiente qui in, debitis velit omnis.</p>
		<p>Debitis itaque quibusdam sit provident nemo officiis saepe sint odio non ut sapiente dicta molestias quasi alias odit consectetur nesciunt rem deserunt aspernatur ab, impedit laborum quos. Hic in saepe magni repellat distinctio pariatur ex sed. Reprehenderit, aut quis velit animi tempore veritatis iusto minus laudantium id quae ut esse?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem soluta maxime ab pariatur quibusdam eaque placeat quidem sunt maiores qui. Quod officiis in soluta doloremque, sunt eveniet praesentium, obcaecati mollitia numquam, earum est excepturi dicta, suscipit iusto. Eveniet obcaecati cum quod accusantium? Harum ratione culpa provident ipsam quis quae expedita explicabo aspernatur itaque repudiandae ad, hic mollitia quisquam. Tenetur, esse.</p>
		<p>Alias eligendi error saepe laborum sed tempora, dolorum, facilis sunt recusandae accusamus minima unde assumenda id repudiandae incidunt explicabo obcaecati? Dolore quos provident accusamus repellendus qui eveniet sapiente maxime inventore molestias delectus dolorem autem aliquam consequuntur, suscipit distinctio obcaecati fuga incidunt minima. Pariatur hic quisquam, deleniti cupiditate quos ab nam explicabo distinctio, dolore nostrum quam aliquid sequi similique sapiente voluptates.</p>
		<p>Placeat eaque magnam repellat iure, illo quo, fuga quam explicabo asperiores laboriosam quasi at laborum sunt. Fugit obcaecati laboriosam non, dolores excepturi consequatur aliquid, voluptates possimus aspernatur quam, rerum aperiam hic quod nam dolore ipsam vel dolorem nesciunt eius atque et. Aliquid quis excepturi ullam, consequuntur illum harum nam necessitatibus repellat magni aliquam. Quae temporibus blanditiis nesciunt amet modi adipisci.</p>
		<p>Ipsum unde accusamus hic nobis ab suscipit quasi cum deserunt asperiores, amet minus, harum pariatur vel repellat tenetur. Autem nemo perspiciatis exercitationem. Cumque saepe, dolor adipisci. Fugiat consequuntur atque nostrum excepturi sequi odit. Vel cum totam, officia suscipit rerum, ab dolor id fugit voluptates, cumque maxime. Nemo fugiat, dolores magni, illum eligendi soluta sequi eaque perferendis distinctio sint corporis et.</p>
	</div>
@stop